config/routes.rb
Rails.application.routes.draw do
  #AUTHENTICATION
  devise_for :users, :controllers => { registrations: 'registrations', omniauth_callbacks: "users/omniauth_callbacks" }

  root 'student_subjects#index'
  get '/subjects/ready', to: 'subjects#ready'

  resources :student_subjects, only: [:index, :show, :create, :destroy] do 
    resources :sections, only: [:show]
    resources :student_standards, only: [:index]
  end
  
  resources :student_standards, only:[:show, :edit, :update]
  
  resources :sections, only: [:edit, :update]
  resources :standards, only: [:create, :update, :destroy]
  resources :users, only: [:index, :show, :update, :destroy] 
  resources :subjects do 
      resources :standards, only: [:show, :new, :edit]
  end

end

app/models/student_standard.rb
class StudentStandard < ApplicationRecord
    belongs_to :standard
    belongs_to :user
    belongs_to :student_subject
    
    enum progress_level: [:beginning, :progressing, :confused, :conquered]
    
    scope :has_progress_level, -> { where.not(progress_level: nil) }

    def self.filter_by_progress_level(progress_level)
        where(progress_level: progress_level)
    end

    def self.filter_by_section(section)
        joins(:standard).where(standards: { section: section} ).order('standards.dot_notation')
    end

end

app/controllers/student_standards_controller.rb
class StudentStandardsController < ApplicationController
    before_action :set_student_standard, only: [:show, :edit, :update]

    def index
        @student_subject = StudentSubject.find(params[:student_subject_id])
        @student_standards = @student_subject.student_standards.has_progress_level
        @student_standards = @student_standards.filter_by_progress_level(params[:progress_level]) if params[:progress_level].present?
    end
    
    def show
        authorize @student_standard
    end

    def edit
    end

    def update
        authorize @student_standard
        if @student_standard.update(student_standard_params)
            redirect_to student_standard_path(@student_standard)
        else
            render "edit"
        end
    end

    private 
    
    def student_standard_params
        params.require(:student_standard).permit(:progress_level, :comments, :evidence, :standard_id)
    end

    def set_student_standard
        @student_standard = StudentStandard.find(params[:id])
    end
end

app/helpers/student_standards_helper.rb
module StudentStandardsHelper

    def student_standard_description(student_standard)
        student_standard.standard.description
    end

    def student_standard_dot_notation(student_standard)
        student_standard.standard.dot_notation
    end

    def student_standard_section(student_standard)
        student_standard.standard.section
    end

    def student_standard_subject(student_standard)
        student_standard.standard.subject
    end

    def student_standard_user_name(student_standard)
        student_standard.user.name
    end

    def progress_column_options(ss)
        if ss.progress_level 
            ss.progress_level
        else 
            if policy(ss).update?
                link_to "Add Progress", edit_student_standard_path(ss)
            else
                "#{ss.user.name} has not entered progress."
            end
        end 
    end

end

app/views/student_standards/_student_standard_table.html.erb
<table id= "student_standard_show">
    <tr>
        <th><b>Subject/Section</b></th>
        <td><%= student_standard_subject(student_standard).title %> / <%= student_standard_section(student_standard).title %></td>
    </tr>
    <tr>
        <th><b>Standard</b></th>
        <td><%= student_standard_description(student_standard) %></td>
    </tr>
    <tr>
        <th><b>Current Progress Level</b></th>
        <td> <%= student_standard.progress_level.titleize if student_standard.progress_level %> </td>
    </tr>
    <tr>
        <th><b>Comments</b></th>
        <td> <%= student_standard.comments %> </td> <br>
    </tr>
    <tr>
        <th><b>Evidence of Learning</b></th>
        <td><%= student_standard.evidence %></td>
    </tr>
</table>

app/views/student_standards/edit.html.erb
<h2>Update Your Progress</h2>
<p><i><%= link_to "Back to Section Standards", student_subject_section_path(@student_standard.student_subject, student_standard_section(@student_standard)) %></i></p>

<%= form_for @student_standard do |f| %>
<table id= "student_standard_show">
    <tr>
        <th>Subject / Section</th>
        <td><%= student_standard_subject(@student_standard).title %> / <%= student_standard_section(@student_standard).title %></td>
    </tr>
    <tr>
        <th>Standard</th>
        <td><%= student_standard_description(@student_standard) %></td>
    </tr>
    
    <tr>
        <th>Which word best describes your current progress with this standard?</th>
        <td> <%= f.select :progress_level, StudentStandard.progress_levels.keys %> </td>
    </tr>
    <tr>
        <th>Comments: (For example, how might you explain this skill or concept?)</th>
        <td> <%= f.text_area :comments %> </td> <br>
    </tr>
    <tr>
        <th>What projects, labs, tests, class activities, etc. relate to this standard?</th>
        <td> <%= f.text_area :evidence %> </td>
    </tr>
     
</table>
<%= f.submit "Save Progress" %>
<% end %>

app/views/student_standards/index.html.erb
<h1>Subject Standards by Progress Level</h1>
<p><i><%= link_to "Back to Subject Sections", student_subject_path(@student_subject) %></i></p>
<% if policy(@student_subject).show? %>
    <%= form_tag student_subject_student_standards_path(@student_subject), method: 'get' %>
        <%= select_tag "progress_level", options_from_collection_for_select(StudentStandard.progress_levels, :last, :first), prompt: "All Progress Levels" %>
    <%= submit_tag "Filter" %>

    <br><br>

    <% @student_standards.each do |student_standard| %>
        <%= render partial: "student_standard_table", locals: {student_standard: student_standard} %>
    <% end %>
<% else %>
    <%= flash[:alert] = "You are not authorized to view this page" %>
<% end %>

app/views/student_standards/show.html.erb
<h1><%= student_standard_user_name(@student_standard)%>'s Learning Progress</h1>
<p><i>
    <%= link_to "Back to Section Standards", student_subject_section_path(@student_standard.student_subject, student_standard_section(@student_standard)) %>
    <% if policy(@student_standard).update? %>
       | <%= link_to "Edit", edit_student_standard_path(@student_standard), method: 'get' %>
    <% end %>
</i></p>

<%= render partial: "student_standard_table", locals: {student_standard: @student_standard} %>