config/routes.rb
Rails.application.routes.draw do
  #AUTHENTICATION
  devise_for :users, :controllers => { registrations: 'registrations', omniauth_callbacks: "users/omniauth_callbacks" }

  root 'student_subjects#index'
  get '/subjects/ready', to: 'subjects#ready'

  resources :student_subjects, only: [:index, :show, :create, :destroy] do 
    resources :sections, only: [:show]
    resources :student_standards, only: [:index]
  end
  
  resources :student_standards, only:[:show, :edit, :update]
  
  resources :sections, only: [:edit, :update]
  resources :standards, only: [:create, :update, :destroy]
  resources :users, only: [:index, :show, :update, :destroy] 
  resources :subjects do 
      resources :standards, only: [:show, :new, :edit]
  end

end

app/models/user.rb
class User < ApplicationRecord
  enum role: [:student, :teacher, :admin]
  after_initialize :set_default_role, :if => :new_record?

  has_many :student_subjects, dependent: :destroy
  has_many :subjects, through: :student_subjects
  has_many :student_standards, dependent: :destroy
  has_many :standards, through: :student_standards

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  def set_default_role
    self.role ||= :student
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

  def self.filter_display(current_user)
    if current_user.admin?
      all.order(:name)
    else
      where(role: "student").order(:name)
    end
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def facebook
        @user = User.from_omniauth(request.env["omniauth.auth"])
        sign_in_and_redirect @user
    end
end

app/controllers/users/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

    private
  
    def sign_up_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
  
    def account_update_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
    end
    
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :update, :destroy]

    def index
      @users = User.filter_display(current_user)
      authorize User
    end

    def show
      authorize @user
    end

    def update
      authorize @user
      if @user.update(user_params)
        redirect_to users_path, :notice => "User updated."
      else
        redirect_to users_path, :alert => "Unable to update user."
      end
    end
    
    def destroy
      authorize @user
      @user.destroy
      redirect_to users_path, :notice => "User deleted."
    end
  
    private
  
    def user_params
      params.require(:user).permit(:role)
    end

    def set_user
      @user = User.find(params[:id])
    end
end

app/views/users/_user.html.erb
<td>
  <%= link_to user.name, user_path(user) %>
</td>
<td>
  <%= user.email %>
</td>
<td>
<% if policy(user).update? %>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit "Change Role"%>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete) unless user == current_user %>
</td>
<% end %>

app/views/users/_user_subjects.html.erb
<table>
    <% user.student_subjects.each do |ss| %>
        <tr>
            <td>
                <%= link_to student_subject_title(ss), student_subject_path(ss) %>
                <ul>
                    <% student_subject_sections(ss).each do |section| %>
                        <li><%= link_to section.title, student_subject_section_path(ss, section) %></li>
                    <% end %>
                </ul>
            </td>
            <td><%= link_to "delete", student_subject_path(ss), :data => { :confirm => "Are you sure? Deleting this subject will also delete the student's progress with the standards in this subject." }, method: "delete" if policy(@user).update? %></td>
        </tr>
    <% end %>
</table>

app/views/users/index.html.erb
<table>
    <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
    </tbody>
</table>

app/views/users/show.html.erb
<h1><%= @user.name %>'s Subjects:</h1>

<p><i><%= link_to "Back to all students", users_path %></i></p>
<p>Click on a section to view progress.</p>

<%= render partial: "user_subjects", locals: {user: @user} %>