config/routes.rb
Rails.application.routes.draw do
  #AUTHENTICATION
  devise_for :users, :controllers => { registrations: 'registrations', omniauth_callbacks: "users/omniauth_callbacks" }

  root 'student_subjects#index'
  get '/subjects/ready', to: 'subjects#ready'

  resources :student_subjects, only: [:index, :show, :create, :destroy] do 
    resources :sections, only: [:show]
    resources :student_standards, only: [:index]
  end
  
  resources :student_standards, only:[:show, :edit, :update]
  
  resources :sections, only: [:edit, :update]
  resources :standards, only: [:create, :update, :destroy]
  resources :users, only: [:index, :show, :update, :destroy] 
  resources :subjects do 
      resources :standards, only: [:show, :new, :edit]
  end

end

app/models/subject.rb
class Subject < ApplicationRecord

    has_many :sections, dependent: :destroy
    has_many :standards, dependent: :destroy
    has_many :student_subjects, dependent: :destroy
    has_many :users, through: :student_subjects

    validates :title, :sections, presence: true
    validates :set_id, presence: true, uniqueness: {message: "has already been added"}

    scope :ready, -> { where('ready = ?', true) }

    def self.collect_set_ids
        all.map {|subject| subject.set_id}
    end
   
    def sections_attributes=(section_attributes)
        section_attributes.each do |i, section_hash|
            if section_hash[:id].present?
                if section_hash[:title].empty?
                    section = Section.find(section_hash[:id])
                    section.destroy
                else
                    section = Section.find(section_hash[:id])
                    section.update(title: section_hash[:title])
                end
            elsif section_hash[:title].present?
                section = Section.create(title: section_hash[:title])
                self.sections << section
            end
        end
    end

    def standards_attributes=(standards_attributes)
        standards_attributes.each do |i, standards_hash|
            if standards_hash[:description] != "0"
                self.standards.create(standards_hash)
            end
        end
    end

end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
    before_action :set_subject, only: [:show, :edit, :update, :destroy]

    def index
        @subjects = Subject.order(:set_id)
        if params["subjects"].present?
            subject = Subject.find(params["subjects"])
            redirect_to subject_path(subject)
        end
    end

    def ready
        @subjects = Subject.ready
        render json: @subjects
    end

    def show
    end

    def new
        @subject = Subject.new
        @subjects_not_added = csp_data("jurisdictions", "B838B98D043045748F3814B9E43CAC85").get_unadded_subjects
        5.times { @subject.sections.build }
    end

    def create
        @subject = Subject.new(subject_params)
        authorize @subject
        if @subject.save
            redirect_to subject_path(@subject)
            flash[:alert] = "Subject created successfully!"
        else
            render :new
        end
    end

    def edit
        2.times { @subject.sections.build }
        standards_not_added = csp_data("standard_sets", @subject.set_id).get_unadded_standards(@subject)
        @new_standards = @subject.standards.build_new_standards(standards_not_added)
    end

    def update
        authorize @subject
        if @subject.update(subject_params)
            if subject_params[:sections_attributes]
                redirect_to edit_subject_path(@subject)
            else
                redirect_to subject_path(@subject)
            end
            flash[:alert] = "Updated successfully!"
        else
            render :edit
        end
    end

    def destroy
        authorize @subject
        @subject.destroy
        redirect_to subjects_path
    end

    private

    def subject_params
        params.require(:subject).permit(:ready, :title, :set_id, sections_attributes: [:title, :id, :subject_id], standards_attributes: [:description, :dot_notation, :section_id, :asn_id])
    end

    def set_subject
        @subject = Subject.find(params[:id])
    end

    def csp_data(resource, set_id)
        CommonStandardsProject.new(resource, set_id)
    end

end

app/helpers/subjects_helper.rb
module SubjectsHelper

    def subject_being_used_alert(subject)
        if subject.student_subjects.present?
            "**This subject is being used by #{subject.student_subjects.size} student(s). Deleting the subject or any of its sections will also delete the standards and student progress associated with it.**"
        end
    end
    
end

app/views/subjects/_add_standards.html.erb
<div class="instructions">
    <legend><b>Add Standards</b></legend>
    <p>The following text comes from the Common Standards Project. If the standard has already been given a number, you can use it to help determine if it is actually a standard (or just a heading), which section it belongs to, and whether or not you want to include it.</p>
        <ul>
            <li>Check the standards that you would like to add.</li>
            <li>If the standard does not have a number, add one to indicate how it should be organized and whether or not it is a sub-standard. </li>
            <ul>
                <li>For example, a substandard of 7.1 would be 7.1a</li> 
            </ul>
            <li>You will be able to edit the text of each standard on the subject's main page.</li>
        </ul>
</div>
    
    <%= form_for object do |f| %>
    <table>
        <tr>
            <th></th>
            <%= content_for :table_heading %>
            <th>Assign Number</th>
            <th>Standard Text</th>
        </tr>
            <% new_standards.each do |standard| %>
                <%= f.fields_for :standards, standard do |sf| %>
                <tr>
                    <%= sf.hidden_field :asn_id %>
                    <%= sf.hidden_field :subject_id, :value=> subject.id if sf.object.section_id %>
                    <td><%= sf.check_box :description, {checked: false}, sf.object.description %></td>
                    <% if sf.object.subject_id %>
                        <td><%= sf.collection_select :section_id, subject.sections.persisted, :id, :title %> </td>
                    <% end %>
                    <td><%= sf.text_field :dot_notation %> </td>
                    <td><%= sf.object.description %></td>
                </tr>
                <% end %>
            <% end %>
    </table>
    <br>
        <%= f.submit %>
    <% end %>

app/views/subjects/_display_subjects.html.erb
<table>
    <tr>
        <th id="skinny-column">Available to Students?</th>
        <th>Title</th>
        <th>Sections</th>
    </tr>
        <% subjects.each do |subject|%>
    <tr>
        <td id="skinny-column"><%= check_box("subject", "ready", {checked: subject.ready?, disabled: true}) %></td>
        <td> 
            <%= link_to subject.title, subject_path(subject) %>
            <% if subject.standards.empty? %>
                <p>(No standards have been added.)</p>
            <% end %>
        </td>
        <td>
            <ul class="section-list">
                <% subject.sections.each do |section| %>
                    <li><%= section.title %></li>
                <% end %>
            </ul>
        </td>
    </tr>
    <% end %>
</table>

app/views/subjects/_form.html.erb
        <fieldset>
        <div class="instructions">
        <legend><b>Subject Title</b></legend>
        <%= f.label :title, "What would you like to name this subject?" %>
        </div>
        <%= f.text_field :title %>
        
        <br> <br>
        
        <div class="instructions">
            <%= yield %>
        </div>
            <%= f.fields_for :sections do |section_form| %>
            <p>
                <%= section_form.label :title %>
                <%= section_form.text_field :title %>
                <%= section_form.hidden_field :id %>
                <%= section_form.hidden_field :subject_id %>
            </p>
            <% end %>
        <%= f.submit %>
        </fieldset>
        <br>
        

app/views/subjects/edit.html.erb
<h1>Edit <%= @subject.title %></h1>

<p class="page-links">
    <%= link_to "Back to Subject Page", subject_path(@subject) %>
    <% if policy(@subject).destroy? %>
        | <%= link_to "Delete", subject_path, :data => { :confirm => "Are you sure you want to delete #{@subject.title}? This action cannot be undone." }, method: "delete", class: "delete" %>
    <% end %>
</p>

<%= render layout: "shared/errors", locals: {object: @subject, path: edit_subject_path(@subject)} do %>
    <p id="flash_alert"> <%= subject_being_used_alert(@subject)%> </p>

    <%= form_for @subject do |f| %>
        <%= render layout: "subjects/form", locals: {f: f} do %>
            <legend><b>Edit Sections</b></legend>
            Removing the title of a section and clicking "Update" will delete the section and all associated standards.
        <% end %>
    <% end %>

    <fieldset>
        <% if @new_standards.empty? %>
            <h3><i>All available standards have been added.</i></h3>
        <% else %>
            <%= content_for :table_heading do %>
                <th>Choose Section</th>
            <% end %>
            <%= render partial: "subjects/add_standards", locals: {subject: @subject, new_standards: @new_standards, object: @subject} %>
        <% end %>
    </fieldset>
    
<% end %>

app/views/subjects/index.html.erb
 <h1>Subjects</h1>

<% if policy(Subject).create? %>
    <%= button_to "Add a New Subject", new_subject_path, method: 'get' %>
<% end %>
<br>

<div class="instructions">
<p>Click on a subject in the table or choose from the dropdown menu to go to that subject's page.</p>
</div>

<%= form_tag subjects_path, method: "get" do %>
    <%= select_tag "subjects", options_from_collection_for_select(@subjects, "id", "title"), prompt: "Choose a subject's page" %>
    <%= submit_tag "Go" %>
<% end %>
<br>

<%= render partial: "display_subjects", locals: {subjects: @subjects} %>

app/views/subjects/new.html.erb
<h1>Add a New Subject</h1>
<p class="page-links"><i><%= link_to "Back to All Subjects", subjects_path %></i></p>

<%= render layout: "shared/errors", locals: {object: @subject, path: new_subject_path} do %>
    <%= form_for @subject do |f| %>
        <%= f.select :set_id, options_for_select(@subjects_not_added), prompt: "Choose Subject" %> <br> <br>
        <%= render layout: "subjects/form", locals: {f: f} do %>
            <legend><b>Add Sections</b></legend>
        <% end %>
    <% end %>
<%end%>

app/views/subjects/show.html.erb
<h2><%= @subject.title %></h2>

<p class="page-links">
    <% if policy(@subject).update? %>
        <%= link_to "Edit Subject", edit_subject_path(@subject) %> |
    <% end %>
    <%= link_to "Back to All Subjects", subjects_path %> 
</p>

<% if policy(@subject).update? %>
    <%= form_for @subject do |f| %>
        <fieldset>
            <%= f.check_box :ready %>
            <%= f.label :ready, "This subject is ready to be made available to students and teachers." %>
            <%= f.submit "Update" %>
        </fieldset>
    <% end %>
<% end %>

<p id="flash_alert"> <%= subject_being_used_alert(@subject)%> </p>

<div class="instructions">
    <p>Standards can be added all at once by clicking on the <%=link_to "Edit Subject", edit_subject_path(@subject) %> link or added by section using the links below.</p>
</div>

<% @subject.sections.each do |section| %>
    <h3><%= section.title %> <i><%= link_to "Add standards to this section", edit_section_path(section) if policy(@subject).update? %></i></h3>
    <% if section.standards.present? %>
        <% order_standards(section.standards).each do |standard| %>
        <ul>
           <li class=<%= "sub-standard" if standard.dot_notation =~ /[a-z]/%>> <%= standard.dot_notation %> <%= standard.description %>
                <%= link_to "edit", edit_subject_standard_path(@subject, standard) if policy(@subject).update? %> </li> 
        </ul>
        <% end %>
    <% end %>
<% end %>