config/routes.rb
Rails.application.routes.draw do
  #AUTHENTICATION
  devise_for :users, :controllers => { registrations: 'registrations', omniauth_callbacks: "users/omniauth_callbacks" }

  root 'student_subjects#index'
  get '/subjects/ready', to: 'subjects#ready'

  resources :student_subjects, only: [:index, :show, :create, :destroy] do 
    resources :sections, only: [:show]
    resources :student_standards, only: [:index]
  end
  
  resources :student_standards, only:[:show, :edit, :update]
  
  resources :sections, only: [:edit, :update]
  resources :standards, only: [:create, :update, :destroy]
  resources :users, only: [:index, :show, :update, :destroy] 
  resources :subjects do 
      resources :standards, only: [:show, :new, :edit]
  end

end

app/models/standard.rb
class Standard < ApplicationRecord
    belongs_to :section
    belongs_to :subject

    has_many :student_standards, dependent: :destroy
    has_many :users, through: :student_standards
   
    validates :description, :dot_notation, :asn_id, presence: true

    def self.collect_descriptions
        all.map {|s| s.description}
    end

    def self.build_new_standards(array)
        array.map do |standard_hash|
            self.new(description: standard_hash[:description], asn_id: standard_hash[:asn_id], dot_notation: standard_hash[:dot_notation])
        end.sort_by {|s| s.asn_id }
    end

end

app/controllers/standards_controller.rb
class StandardsController < ApplicationController
    before_action :set_standard

    def edit
        @subject = @standard.subject
    end

    def update
        if @standard.update(standard_params)
            redirect_to subject_path(@standard.subject)
        else
            render :edit
        end
    end

    def destroy
        @standard.destroy
        redirect_to subject_path(@standard.subject)
    end

    private

    def standard_params
        params.require(:standard).permit(:description, :dot_notation, :section_id, :asn_id)
    end

    def set_standard
        @standard = Standard.find(params[:id])
    end

end

app/helpers/standards_helper.rb
module StandardsHelper

    def section_title(standard)
        standard.section.title
    end

    def subject_title(standard)
        standard.subject.title
    end

    def order_standards(standards)
        standards.order(:asn_id)
    end

end

app/views/standards/_form.html.erb
<%= form_for standard do |f| %>
    <b><%= f.label :section_id, "Section" %></b>
    <%= f.collection_select(:section_id, subject.sections, :id, :title) %> <br> <br>
    <b><%= f.label :asn_id, "ASN ID:" %></b>
    <%= f.text_field :asn_id %> <br>
    *This is number used by the Common Standards Project to order the standards. If the standards are not appearing in the order you would like, try changing their ASN IDs. <br> <br>
    <b><%= f.label :dot_notation, "Number:" %></b>
    <%= f.text_field :dot_notation %> <br> <br>
    <b><%= f.label :description, "Standard Description:" %></b> <br>
    <%= f.text_area :description %> <br><br>
    <%= f.submit %> 
<% end %>

app/views/standards/edit.html.erb
<h2>Edit <%= section_title(@standard) %> Standard</h2>

<%= render layout: "shared/errors", locals: {object: @standard, path: edit_subject_standard_path(@standard.subject, @standard) } do %>
    <i><%= link_to "Cancel", subject_path(@subject) %></i>
    <% if policy(@standard).destroy? %>
        <i> | <%= link_to "Delete", standard_path, :data => { :confirm => "Are you sure you want to delete this standard? This action cannot be undone." }, method: "delete", class: "delete" %></i>
    <% end %>

    <br> <br>

    <%= render partial: "form", locals: {standard: @standard, subject: @subject} %>
        
<% end %>

app/views/standards/index.html.erb
<%= form_tag standards_path, method: "get" do %>
    <%= select_tag "subjects", options_from_collection_for_select(@subjects, "id", "title"), prompt: "Display All" %>
    <%= submit_tag "Filter by Subject" %>
<% end %>
<br>

<table>
    <thead>
        <tr>
            <th>Standard</th>
            <th>Subject</th>
            <th>Section</th>
        </tr>
    </thead>
    <tbody>
        <% @standards.each do |s| %>
        <tr>
            <td><%= s.dot_notation %> <%= s.description %></td>
            <td><%= subject_title(s) %></td>
            <td> <%= section_title(s) %> </td>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/standards/old_form.html.erb
<%= form_for standard do |f| %>
    <% standards_array.each_with_index do |standard_hash, index| %>
        <fieldset>
            <%= f.fields_for :standards_attributes do |s| %>
                <i><%= s.label "[#{index}][include]", "Check if you DO NOT want to include this standard." %></i>
                <%= check_box_tag "standard[standards_attributes][[#{index}][include]]", "no" %> <br>
                <b><%= s.label "[#{index}][dot_notation]", "Number (required):" %></b>
                <%= s.text_field "[#{index}][dot_notation]", :required => true %>  <br>
                <b><%= s.label "[#{index}][section_id]", "Section:" %></b>
                <%= s.select "[#{index}][section_id]", options_from_collection_for_select(sections, "id", "title") %> <br>
                <b><%= s.label "[#{index}][description]", "Description:" %></b>
                <%= standard_hash[:description] %>
                <%= s.hidden_field "[#{index}][description]", :value => standard_hash[:description] %>
                <%= s.hidden_field "[#{index}][asn_id]", :value => standard_hash[:asn_id] %>
                <%= s.hidden_field "[#{index}][subject_id]", value: subject.id %>
            <% end %>
        </fieldset>
    <% end %>
    <br>
<%= f.submit "Add These Standards"%>
<% end %>